/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTwitterIndexRouteImport } from './routes/_authenticated/twitter/index'
import { Route as AuthenticatedTiktokIndexRouteImport } from './routes/_authenticated/tiktok/index'
import { Route as AuthenticatedTagsIndexRouteImport } from './routes/_authenticated/tags/index'
import { Route as AuthenticatedLinksIndexRouteImport } from './routes/_authenticated/links/index'
import { Route as AuthenticatedInstagramIndexRouteImport } from './routes/_authenticated/instagram/index'
import { Route as AuthenticatedImportsIndexRouteImport } from './routes/_authenticated/imports/index'
import { Route as AuthenticatedFileManagerIndexRouteImport } from './routes/_authenticated/file-manager/index'
import { Route as AuthenticatedDownloadsIndexRouteImport } from './routes/_authenticated/downloads/index'
import { Route as AuthenticatedCollectionsIndexRouteImport } from './routes/_authenticated/collections/index'
import { Route as AuthenticatedInstagramVirtualWindowRouteImport } from './routes/_authenticated/instagram/virtual-window'
import { Route as AuthenticatedInstagramVirtualRouteImport } from './routes/_authenticated/instagram/virtual'
import { Route as AuthenticatedInstagramTempRouteImport } from './routes/_authenticated/instagram/temp'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTwitterIndexRoute =
  AuthenticatedTwitterIndexRouteImport.update({
    id: '/twitter/',
    path: '/twitter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTiktokIndexRoute =
  AuthenticatedTiktokIndexRouteImport.update({
    id: '/tiktok/',
    path: '/tiktok/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTagsIndexRoute = AuthenticatedTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinksIndexRoute = AuthenticatedLinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInstagramIndexRoute =
  AuthenticatedInstagramIndexRouteImport.update({
    id: '/instagram/',
    path: '/instagram/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportsIndexRoute =
  AuthenticatedImportsIndexRouteImport.update({
    id: '/imports/',
    path: '/imports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFileManagerIndexRoute =
  AuthenticatedFileManagerIndexRouteImport.update({
    id: '/file-manager/',
    path: '/file-manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDownloadsIndexRoute =
  AuthenticatedDownloadsIndexRouteImport.update({
    id: '/downloads/',
    path: '/downloads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCollectionsIndexRoute =
  AuthenticatedCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstagramVirtualWindowRoute =
  AuthenticatedInstagramVirtualWindowRouteImport.update({
    id: '/instagram/virtual-window',
    path: '/instagram/virtual-window',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstagramVirtualRoute =
  AuthenticatedInstagramVirtualRouteImport.update({
    id: '/instagram/virtual',
    path: '/instagram/virtual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInstagramTempRoute =
  AuthenticatedInstagramTempRouteImport.update({
    id: '/instagram/temp',
    path: '/instagram/temp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/sign-in': typeof AuthSignInRoute
  '/instagram/temp': typeof AuthenticatedInstagramTempRoute
  '/instagram/virtual': typeof AuthenticatedInstagramVirtualRoute
  '/instagram/virtual-window': typeof AuthenticatedInstagramVirtualWindowRoute
  '/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/downloads/': typeof AuthenticatedDownloadsIndexRoute
  '/file-manager/': typeof AuthenticatedFileManagerIndexRoute
  '/imports/': typeof AuthenticatedImportsIndexRoute
  '/instagram/': typeof AuthenticatedInstagramIndexRoute
  '/links/': typeof AuthenticatedLinksIndexRoute
  '/tags/': typeof AuthenticatedTagsIndexRoute
  '/tiktok/': typeof AuthenticatedTiktokIndexRoute
  '/twitter/': typeof AuthenticatedTwitterIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/sign-in': typeof AuthSignInRoute
  '/': typeof AuthenticatedIndexRoute
  '/instagram/temp': typeof AuthenticatedInstagramTempRoute
  '/instagram/virtual': typeof AuthenticatedInstagramVirtualRoute
  '/instagram/virtual-window': typeof AuthenticatedInstagramVirtualWindowRoute
  '/collections': typeof AuthenticatedCollectionsIndexRoute
  '/downloads': typeof AuthenticatedDownloadsIndexRoute
  '/file-manager': typeof AuthenticatedFileManagerIndexRoute
  '/imports': typeof AuthenticatedImportsIndexRoute
  '/instagram': typeof AuthenticatedInstagramIndexRoute
  '/links': typeof AuthenticatedLinksIndexRoute
  '/tags': typeof AuthenticatedTagsIndexRoute
  '/tiktok': typeof AuthenticatedTiktokIndexRoute
  '/twitter': typeof AuthenticatedTwitterIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/instagram/temp': typeof AuthenticatedInstagramTempRoute
  '/_authenticated/instagram/virtual': typeof AuthenticatedInstagramVirtualRoute
  '/_authenticated/instagram/virtual-window': typeof AuthenticatedInstagramVirtualWindowRoute
  '/_authenticated/collections/': typeof AuthenticatedCollectionsIndexRoute
  '/_authenticated/downloads/': typeof AuthenticatedDownloadsIndexRoute
  '/_authenticated/file-manager/': typeof AuthenticatedFileManagerIndexRoute
  '/_authenticated/imports/': typeof AuthenticatedImportsIndexRoute
  '/_authenticated/instagram/': typeof AuthenticatedInstagramIndexRoute
  '/_authenticated/links/': typeof AuthenticatedLinksIndexRoute
  '/_authenticated/tags/': typeof AuthenticatedTagsIndexRoute
  '/_authenticated/tiktok/': typeof AuthenticatedTiktokIndexRoute
  '/_authenticated/twitter/': typeof AuthenticatedTwitterIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/sign-in'
    | '/instagram/temp'
    | '/instagram/virtual'
    | '/instagram/virtual-window'
    | '/collections/'
    | '/downloads/'
    | '/file-manager/'
    | '/imports/'
    | '/instagram/'
    | '/links/'
    | '/tags/'
    | '/tiktok/'
    | '/twitter/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/sign-in'
    | '/'
    | '/instagram/temp'
    | '/instagram/virtual'
    | '/instagram/virtual-window'
    | '/collections'
    | '/downloads'
    | '/file-manager'
    | '/imports'
    | '/instagram'
    | '/links'
    | '/tags'
    | '/tiktok'
    | '/twitter'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_auth/sign-in'
    | '/_authenticated/'
    | '/_authenticated/instagram/temp'
    | '/_authenticated/instagram/virtual'
    | '/_authenticated/instagram/virtual-window'
    | '/_authenticated/collections/'
    | '/_authenticated/downloads/'
    | '/_authenticated/file-manager/'
    | '/_authenticated/imports/'
    | '/_authenticated/instagram/'
    | '/_authenticated/links/'
    | '/_authenticated/tags/'
    | '/_authenticated/tiktok/'
    | '/_authenticated/twitter/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/twitter/': {
      id: '/_authenticated/twitter/'
      path: '/twitter'
      fullPath: '/twitter/'
      preLoaderRoute: typeof AuthenticatedTwitterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tiktok/': {
      id: '/_authenticated/tiktok/'
      path: '/tiktok'
      fullPath: '/tiktok/'
      preLoaderRoute: typeof AuthenticatedTiktokIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tags/': {
      id: '/_authenticated/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AuthenticatedTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/links/': {
      id: '/_authenticated/links/'
      path: '/links'
      fullPath: '/links/'
      preLoaderRoute: typeof AuthenticatedLinksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram/': {
      id: '/_authenticated/instagram/'
      path: '/instagram'
      fullPath: '/instagram/'
      preLoaderRoute: typeof AuthenticatedInstagramIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imports/': {
      id: '/_authenticated/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof AuthenticatedImportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/file-manager/': {
      id: '/_authenticated/file-manager/'
      path: '/file-manager'
      fullPath: '/file-manager/'
      preLoaderRoute: typeof AuthenticatedFileManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/downloads/': {
      id: '/_authenticated/downloads/'
      path: '/downloads'
      fullPath: '/downloads/'
      preLoaderRoute: typeof AuthenticatedDownloadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/collections/': {
      id: '/_authenticated/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AuthenticatedCollectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram/virtual-window': {
      id: '/_authenticated/instagram/virtual-window'
      path: '/instagram/virtual-window'
      fullPath: '/instagram/virtual-window'
      preLoaderRoute: typeof AuthenticatedInstagramVirtualWindowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram/virtual': {
      id: '/_authenticated/instagram/virtual'
      path: '/instagram/virtual'
      fullPath: '/instagram/virtual'
      preLoaderRoute: typeof AuthenticatedInstagramVirtualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/instagram/temp': {
      id: '/_authenticated/instagram/temp'
      path: '/instagram/temp'
      fullPath: '/instagram/temp'
      preLoaderRoute: typeof AuthenticatedInstagramTempRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInstagramTempRoute: typeof AuthenticatedInstagramTempRoute
  AuthenticatedInstagramVirtualRoute: typeof AuthenticatedInstagramVirtualRoute
  AuthenticatedInstagramVirtualWindowRoute: typeof AuthenticatedInstagramVirtualWindowRoute
  AuthenticatedCollectionsIndexRoute: typeof AuthenticatedCollectionsIndexRoute
  AuthenticatedDownloadsIndexRoute: typeof AuthenticatedDownloadsIndexRoute
  AuthenticatedFileManagerIndexRoute: typeof AuthenticatedFileManagerIndexRoute
  AuthenticatedImportsIndexRoute: typeof AuthenticatedImportsIndexRoute
  AuthenticatedInstagramIndexRoute: typeof AuthenticatedInstagramIndexRoute
  AuthenticatedLinksIndexRoute: typeof AuthenticatedLinksIndexRoute
  AuthenticatedTagsIndexRoute: typeof AuthenticatedTagsIndexRoute
  AuthenticatedTiktokIndexRoute: typeof AuthenticatedTiktokIndexRoute
  AuthenticatedTwitterIndexRoute: typeof AuthenticatedTwitterIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInstagramTempRoute: AuthenticatedInstagramTempRoute,
  AuthenticatedInstagramVirtualRoute: AuthenticatedInstagramVirtualRoute,
  AuthenticatedInstagramVirtualWindowRoute:
    AuthenticatedInstagramVirtualWindowRoute,
  AuthenticatedCollectionsIndexRoute: AuthenticatedCollectionsIndexRoute,
  AuthenticatedDownloadsIndexRoute: AuthenticatedDownloadsIndexRoute,
  AuthenticatedFileManagerIndexRoute: AuthenticatedFileManagerIndexRoute,
  AuthenticatedImportsIndexRoute: AuthenticatedImportsIndexRoute,
  AuthenticatedInstagramIndexRoute: AuthenticatedInstagramIndexRoute,
  AuthenticatedLinksIndexRoute: AuthenticatedLinksIndexRoute,
  AuthenticatedTagsIndexRoute: AuthenticatedTagsIndexRoute,
  AuthenticatedTiktokIndexRoute: AuthenticatedTiktokIndexRoute,
  AuthenticatedTwitterIndexRoute: AuthenticatedTwitterIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
